#!/usr/bin/env bash

if [[ $# != 2 ]]; then
  echo "usage: $0 email password"
  exit 1
fi

curl -X POST \
  -H "Content-Type: application/json" \
  -d "{ \"email\": \"$1\", \"password\": \"$2\" }" \
  http://localhost:3000/api/users/login
