#!/usr/bin/env bash

if [[ $# != 2 ]]; then
  echo "usage: $0 communication_id auth_token"
  exit 1
fi

curl -s -X PATCH "http://localhost:3000/api/communications/$1" \
  -H "Authorization: Bearer $2" \
  -H "Content-Type: application/json" \
  -d '{"status": "sent"}'
